### ISSUE TITLE
some input gets ignored and disappears, then re-appears on the next input

### ISSUE THREAD

**Issue by Zhongzhou** [CampusGPT-ai/GAI_Academic_Advising_Assistant_MVP#35]
![image](https://github.com/CampusGPT-ai/GAI_Academic_Advising_Assistant_MVP/assets/5183025/dc70d0b2-c546-42ce-afe7-f24d3a16067e)

The first question on the screen shot (the third in the queue) disappeared temporarily, then re-appeared after the 4th question was added.

**Comment by marycampus** [comment]
--reclassifying as bug, assigning to myself

**Comment by marycampus** [comment]
after some testing, I think what is happening here is that the enter key is getting pressed or a new question is submitted before the old conversation has completely finished streaming.  I am going to try disabling submitting new questions until streaming is completed and see if this resolves the issue.
