### ISSUE TITLE
Order of input and output reversed on screen

### ISSUE THREAD

**Issue by Zhongzhou** [CampusGPT-ai/GAI_Academic_Advising_Assistant_MVP#36]
![image](https://github.com/CampusGPT-ai/GAI_Academic_Advising_Assistant_MVP/assets/5183025/95ca98c2-9d28-4fe0-87ac-797b4ee0adf9)
As shown in screenshot. The question is under the answer, but should be above it.

**Comment by marycampus** [comment]
Thanks Chen! I will try to repro

--reclassifying to bug

**Comment by marycampus** [comment]
closing as resolved in branch 38 (fixing loading states)
