### ISSUE TITLE
Found room scheduling service when asked for upper level electives

### ISSUE THREAD

**Issue by Zhongzhou** [CampusGPT-ai/GAI_Academic_Advising_Assistant_MVP#41]
![image](https://github.com/CampusGPT-ai/GAI_Academic_Advising_Assistant_MVP/assets/5183025/7b7c95fc-736f-4656-a5d7-0a112f009c48)

Probably because it lacks context and things that upper level means up-stairs? This is an unclear question to begin with, and the best response would be a follow up question.

**Comment by marycampus** [comment]
i'm not able to repro this - but I am thinking that this was a one-off bad response. I'm going to close this, not because it's not important but because I'm going to put it under the umbrella of model accuracy.
