### ISSUE TITLE
Mismatched citations

### ISSUE THREAD

**Issue by Zhongzhou** [CampusGPT-ai/GAI_Academic_Advising_Assistant_MVP#45]
![image](https://github.com/CampusGPT-ai/GAI_Academic_Advising_Assistant_MVP/assets/5183025/5cbfc808-51e4-4d63-9356-628dcedbc1f8)

citation 3 in the response is not the same as citation 3 listed in the citations. Maybe it was going over an old page?

**Comment by Zhongzhou** [comment]
![image](https://github.com/CampusGPT-ai/GAI_Academic_Advising_Assistant_MVP/assets/5183025/97de93b2-3dcf-420d-b8b3-8e3ac44eff59)
Here, none of the three sources are the advising service office listed in the citation. The title of the citations are also not very hepful nor descriptive.

**Comment by marycampus** [comment]
hey - actually the prompt is telling GPT to reference the citations in the reply, and for some reason it's just not doing a good job - it's sometimes putting good info, and sometimes making things up.  I'm going to remove this from the prompt for now - we will still include citations, but not in the text

**Comment by marycampus** [comment]
closing - handling in branch 23
